version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_LIQUIBASE_CHANGE-LOG: classpath:liquibase/db.changelog-master.xml
    depends_on:
      - postgres

volumes:
  postgres-data:
